### ISSUE TITLE
Bump supported go versions

### ISSUE THREAD

**Issue by akijakya** [bank-vaults/vault-sdk#207]
### Preflight Checklist

- [X] I have checked the [issue tracker](https://www.github.com/bank-vaults/vault-sdk/issues) and found no issue that matches the one I want to submit.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

Currently go 1.17-20 versions are tested, but recent dependabot bump(s) fail with go 1.17.

### Proposed Solution

Consider dropping go 1.17 support and test with the latest 4 minor versions (go 1.18-21).

### Additional Information

E.g. here is a failing dependabot PR: https://github.com/bank-vaults/vault-sdk/pull/214

**Comment by ramizpolic** [comment]
I think we can keep the go version as is for now since there are no hard requirements on bumping it. 
However, I would consider adding `go1.21` to the test matrix as well.

**Comment by ramizpolic** [comment]
+1 ftom me, feel free to update all go.mod deps once the support for go1.17 is dropped
