### ISSUE TITLE
Use Vault-supported official auth libraries

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/vault-sdk#58]
Right now, we maintain code for a bunch of different auth providers.

It looks like some of those providers may be available under Vault itself: https://github.com/hashicorp/vault/tree/main/api/auth

Investigate if we can use those libraries to replace some of our code with officially maintained versions.

This might also be interesting: https://github.com/hashicorp/go-secure-stdlib/tree/main/awsutil

**Comment by akijakya** [comment]
The packages under vault/api/auth could be useful indeed! Right now we are putting together a map with login data for each of the auth methods, and then we acquire the api [secret](https://github.com/bank-vaults/vault-sdk/blob/171ff59352d5b5cd8228f39714056a4dc8b5bae2/vault/client.go#L582) by manually doing a write operation on the respective auth methods `/login` path. With this lib, the whole operation could be simplified by [creating](https://github.com/hashicorp/vault/blob/4d7d1755309c753a3d53d637048cc23dc474d876/api/auth/aws/aws.go#L60) an `*Auth` object with some options and [call](https://github.com/hashicorp/vault/blob/4d7d1755309c753a3d53d637048cc23dc474d876/api/auth/aws/aws.go#LL90C4-L90C4) `Login()` on them, so we don't use the provider's SDKs, or packages directly.

**Comment by ramizpolic** [comment]
The latest Vault API includes auth libraries and the current changes will be based on using these auth APIs instead of our own

**Comment by ramizpolic** [comment]
todo @ramizpolic: check how we can use "temporary docker images" for tests from PRs

**Comment by ramizpolic** [comment]
Meeting notes

### TODO
- Test against as many providers as possible (including Azure/GCP/AWS) with different authentication options

**Comment by ramizpolic** [comment]
### Notes
- Get access to other environments (GCP + AWS) to test against
